---
# tasks file for clickhouse-role
- name: Install GPG-key for Clickhouse
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.clickhouse.com/CLICKHOUSE-KEY.GPG

- name: Add Clickhouse repo
  ansible.builtin.command: "dnf config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo"

- name: Get clickhouse distrib
  ansible.builtin.get_url:
    url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
    dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
  with_items: "{{ clickhouse_packages }}"

- name: Get clickhouse distrib
  ansible.builtin.get_url:
    url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
    dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"

- name: Install clickhouse packages
  ansible.builtin.dnf:
    enablerepo: clickhouse-stable
    name: "{{ item }}-{{ clickhouse_version }}"
    state: present
  with_items: "{{ clickhouse_packages }}"
  notify: Start clickhouse service
- name: Start clickhouse service
  ansible.builtin.meta: flush_handlers
- name: Pause
  ansible.builtin.pause:
    minutes: 1
- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc !=82
  changed_when: create_db.rc == 0
